const { contextBridge, ipcRenderer } = require('electron');

// Inject Supabase env for shared cloud backend (same project as Netlify/Android).
const isLocalInstaller = process.env.SHOP_POS_LOCAL_INSTALLER === '1';
const supabaseUrl = process.env.SHOP_POS_SUPABASE_URL || process.env.SUPABASE_URL || '';
const supabaseAnon = process.env.SHOP_POS_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY || '';
const rpcUrl = isLocalInstaller ? '' : (process.env.SHOP_POS_RPC_URL || process.env.RPC_URL || '');
const syncUrl = process.env.SHOP_POS_SYNC_URL || 'https://chisafood.up.railway.app';
contextBridge.exposeInMainWorld('__SHOP_POS_LOCAL_INSTALLER__', isLocalInstaller);
contextBridge.exposeInMainWorld('__SHOP_POS_ENV__', {
  SUPABASE_URL: supabaseUrl,
  SUPABASE_ANON_KEY: supabaseAnon,
  SHOP_POS_SUPABASE_URL: supabaseUrl,
  SHOP_POS_SUPABASE_ANON_KEY: supabaseAnon,
  RPC_URL: rpcUrl,
  SHOP_POS_RPC_URL: rpcUrl,
  SHOP_POS_SYNC_URL: syncUrl,
  SHOP_POS_CLOUD_URL: syncUrl
});
contextBridge.exposeInMainWorld('__SHOP_POS_USE_SUPABASE__', isLocalInstaller ? false : (!!(supabaseUrl && supabaseAnon) || !!rpcUrl));

const channels = [
  'app:quit',
  'auth:login', 'auth:logout', 'auth:getUsers', 'auth:createUser', 'auth:updateUser', 'auth:deleteUser', 'auth:permanentlyDeleteUser', 'auth:verifySession', 'auth:session',
  'auth:hasRecovery', 'auth:getRecoveryStatus', 'auth:recoverVerify', 'auth:recoverReset', 'auth:seedInstallerAccount', 'auth:setRecoverySecret', 'auth:factoryReset',
  'auth:clearOperationalData', 'auth:listClearDataCategories',
  'auth:verifyBookkeepingPassword', 'auth:setBookkeepingPassword',
  'settings:get', 'settings:getParsed', 'settings:getOperatingHours', 'settings:getMenuHighlights', 'settings:saveMenuHighlights', 'settings:save', 'settings:saveJson', 'settings:completeSetup',
  'settings:detectExistingBusiness', 'settings:adoptExistingBusiness',
  'settings:submitRequest', 'settings:getPendingRequests', 'settings:getRequestHistory', 'settings:approveRequest', 'settings:rejectRequest',
  'settings:updateRequest', 'settings:deleteRequest',
  'categories:get', 'categories:save', 'categories:delete',
  'products:get', 'products:getOne', 'products:getByBarcode', 'products:save', 'products:delete', 'products:import', 'products:calcRecipe',
  'products:saveOtherSell', 'products:suggestPrice',
  'stock:adjust', 'stock:recordAdjustment', 'stock:listAdjustments', 'stock:history',
  'sales:complete', 'sales:get', 'sales:getByReceipt', 'sales:hold', 'sales:getHeld', 'sales:deleteHeld',
  'returns:process', 'returns:get',
  'expenses:get', 'expenses:dashboardStats', 'expenses:save', 'expenses:delete',
  'expenses:getOne', 'expenses:getCategories', 'expenses:saveCategories',
  'expenses:parseReceipt', 'expenses:budgets', 'expenses:budgetStatus', 'expenses:saveBudget', 'expenses:deleteBudget',
  'expenses:recurring', 'expenses:saveRecurring', 'expenses:deleteRecurring', 'expenses:postRecurring',
  'expenses:ownerFundings', 'expenses:recordOwnerFunding',
  'customers:get', 'customers:getOne', 'customers:save', 'customers:delete', 'customers:history',
  'suppliers:get', 'suppliers:save', 'suppliers:delete', 'suppliers:pay', 'suppliers:payments',
  'po:get', 'po:getDetail', 'po:save', 'po:receive', 'po:receivePartial', 'po:delete', 'po:update',
  'dashboard:stats', 'inventory:stats', 'analytics:sales',
  'shifts:open', 'shifts:close', 'shifts:closePreview', 'shifts:get', 'shifts:getOpenAll',
  'shifts:forceClose', 'shifts:update', 'shifts:delete', 'shifts:current',
  'shifts:cashDrop', 'shifts:cashDrops', 'shifts:confirmCashDrop',
  'settings:getSalesTargets', 'settings:saveSalesTargets', 'settings:getTodayTargetProgress',
  'settings:getSalesTargetHistory', 'settings:getSalesTargetInsights',
  'settings:saveSalesTargetAlertSettings', 'settings:saveSalesTargetDayNote',
  'settings:getShiftSettings', 'settings:enforceCashoutDeadlines', 'settings:saveShiftSettings',
  'reports:sales', 'reports:profit', 'reports:cashier', 'reports:cashierDetail', 'reports:product', 'reports:stock', 'reports:expenses',
  'reports:hourly', 'reports:category', 'reports:brand', 'reports:payments', 'reports:employee',
  'reports:discounts', 'reports:voids', 'reports:movements', 'reports:profitDash',
  'reports:giftcards', 'reports:layby', 'reports:quotes', 'reports:onaccount', 'reports:cashup', 'reports:operating',
  'audit:get', 'notifications:get', 'notifications:read', 'notifications:readAll',
  'notifications:createTest', 'notifications:ensureDemoSound', 'notifications:refreshPaymentDue',
  'notifications:ackEvent', 'notifications:ackEvents', 'notifications:listAcked',
  'search:global', 'printers:list', 'printers:listByConnection', 'printers:connect', 'printers:status',
  'backup:create', 'backup:restore', 'backup:restoreSetup', 'backup:export',
  'deviceSettings:get', 'deviceSettings:save',
  'print:receipt', 'print:kitchen', 'print:a4', 'print:preview', 'print:htmlToPdf', 'print:openDrawer', 'print:barcode',
  'kitchen:openDisplay', 'kitchen:closeDisplay', 'kitchen:refreshDisplay',
  'customer:openDisplay', 'customer:closeDisplay', 'customer:refreshDisplay',
  'export:excel', 'export:pdf', 'export:print',
  'file:selectDocument', 'file:persistMobileDocument', 'file:selectImage', 'file:save', 'file:openPdf', 'file:printPdf', 'file:openPath', 'file:openExternal',
  'file:copyImageToClipboard', 'file:shareNative', 'file:getImageDataUrl', 'file:selectAudio', 'file:getAudioDataUrl',
  'db:health', 'db:storageMonitor', 'db:storageSnapshot', 'db:optimize', 'db:repair', 'db:resetDemo', 'db:archive', 'db:recalcStock', 'db:logs',
  'quotes:get', 'quotes:getOne', 'quotes:save', 'quotes:convert', 'quotes:delete', 'quotes:markConverted', 'quotes:reactivate', 'quotes:pdf',
  'layby:get', 'layby:getOne', 'layby:create', 'layby:pay', 'layby:refund', 'layby:getSettings', 'layby:saveSettings',
  'taken:list', 'taken:summary', 'taken:pay',
  'giftcards:get', 'giftcards:create', 'giftcards:update', 'giftcards:delete', 'giftcards:check',
  'giftcards:approve', 'giftcards:reject', 'giftcards:getSettings', 'giftcards:saveSettings',
  'loyalty:history', 'loyalty:syncMissing', 'loyalty:listRestorable', 'loyalty:restoreExpired', 'credit:ledger', 'credit:pay',
  'operating:log',
  'stockcount:get', 'stockcount:getOne', 'stockcount:create', 'stockcount:updateLine', 'stockcount:complete',
  'waste:get', 'waste:record', 'waste:approve', 'waste:reject', 'waste:returnStock',
  'cashup:get', 'cashup:getOne', 'cashup:byShift', 'cashup:create', 'cashup:approve', 'cashup:update', 'cashup:delete', 'cashup:summary', 'cashup:pdf',
  'automation:get', 'automation:save', 'automation:delete',
  'customfields:get', 'customfields:save', 'customfields:delete', 'customfields:values', 'customfields:saveValues',
  'tables:get', 'tables:save', 'tables:release', 'kitchen:get', 'kitchen:status', 'kitchen:create',
  'dev:info', 'dev:activate', 'dev:resetTrial',
  'audit:salesList', 'audit:searchSales', 'audit:voidSale', 'audit:updateSale', 'audit:deleteSale', 'audit:deleteSalesBulk',
  'audit:soldProducts', 'audit:lowPerformance',
  'audit:returnDetail', 'audit:returnsList', 'audit:priceHistory', 'audit:timeline', 'audit:exceptions',
  'audit:alerts', 'audit:dashboard', 'audit:dailyClosing', 'audit:customerSummary', 'audit:topCustomers',
  'audit:returnReasons', 'audit:reopenReturn', 'auth:verifyManagerPin',
  'security:generateCode', 'security:getTodayCode', 'security:verifyCode',
  'staff:getEmployees', 'staff:getEmployee', 'staff:getEmployeeByUserId', 'staff:saveEmployee', 'staff:deleteEmployee',
  'staff:login', 'staff:adminOpen', 'staff:logout', 'staff:validateLinks', 'staff:saveSelfie', 'staff:getSelfies', 'staff:getSelfie', 'staff:updateSelfie', 'staff:deleteSelfie',
  'staff:clock', 'staff:getAttendance', 'staff:getTodayAttendance', 'staff:getPortalFeed',
  'staff:getLeave', 'staff:getAllLeave', 'staff:saveLeave', 'staff:approveLeave', 'staff:leavePdf',
  'staff:submitLeaveProof', 'staff:confirmLeaveProof', 'staff:getPendingLeaveProofs',
  'staff:getLeaveBalance', 'staff:getLeavePolicy',
  'staff:getPayroll', 'staff:generatePayroll', 'staff:paySalary',
  'staff:getPayrollDashboard', 'staff:previewPayroll', 'staff:getMissedClockOutInbox', 'staff:resolveMissedClockOut',
  'staff:saveWorkSchedule', 'staff:updateAttendance',
  'staff:deleteAttendance', 'staff:createAttendance', 'staff:addAttendancePenalty', 'staff:getAttendancePenalties',
  'staff:cancelAttendancePenalty', 'staff:getAttendanceSummary',
  'staff:saveHrDocument', 'staff:getHrDocuments', 'staff:getHrDocument', 'staff:buildHrDocumentHtml',
  'staff:getSchedules', 'staff:saveSchedule', 'staff:deleteSchedule', 'staff:autoShifts',
  'staff:getDocuments', 'staff:saveDocument', 'staff:getDisciplinary', 'staff:saveDisciplinary',
  'staff:respondDisciplinary', 'staff:getAllDisciplinary', 'staff:disciplinaryPdf', 'staff:markDisciplinaryWa',
  'staff:getCustomerPhoneReport', 'staff:customerPhoneReportPdf',
  'staff:getPerformance', 'staff:getNotifications', 'staff:payslipPdf', 'staff:schedulePdf', 'staff:schedulePrintHtml', 'staff:reportPdf',
  'staff:getLoginEvents', 'staff:recordLogout',
  'staff:validateAccount',
  'hr:getEvalCategories', 'hr:populateContract', 'hr:fillContractBody', 'hr:getContractTemplates', 'hr:saveContractTemplate', 'hr:deleteContractTemplate',
  'hr:getContracts', 'hr:getContract', 'hr:saveContract', 'hr:signContract', 'hr:contractPdf',
  'hr:listLeases', 'hr:getLease', 'hr:saveLease', 'hr:deleteLease', 'hr:uploadLease', 'hr:leasePdf',
  'hr:openContractResign', 'hr:attachContractDoc', 'hr:getContractsForEmployee',
  'salaryClaims:list', 'salaryClaims:get', 'salaryClaims:save', 'salaryClaims:delete',
  'salaryClaims:claim', 'salaryClaims:approve', 'salaryClaims:reject', 'salaryClaims:markPaid',
  'salaryClaims:pdf', 'salaryClaims:fromPayroll',
  'hr:getProbations', 'hr:getProbation', 'hr:saveProbation', 'hr:deleteProbation', 'hr:getDecisionRules', 'hr:saveDecisionRule',
  'hr:saveDailyEvaluation', 'hr:getEvaluationHistory', 'hr:getRecommendation', 'hr:finalProbationDecision',
  'hr:getProbationDashboard', 'hr:probationPdf', 'hr:evaluationReportPdf', 'hr:probationLetterPdf', 'hr:getPersonnelFile',
  'hrTraining:getTemplates', 'hrTraining:saveTemplate', 'hrTraining:deleteTemplate', 'hrTraining:getRecords', 'hrTraining:saveRecord',
  'hrTraining:deleteRecord', 'hrTraining:saveEvaluation', 'hrTraining:evalPdf', 'hrTraining:getSubmissions', 'hrTraining:assignTemplate', 'hrTraining:submitForm', 'hrTraining:reviewSubmission', 'hrTraining:updateSubmission', 'hrTraining:deleteSubmission', 'hrTraining:attachDoc',
  'employeeOfMonth:getScores', 'employeeOfMonth:getRecord', 'employeeOfMonth:save', 'employeeOfMonth:certificate', 'employeeOfMonth:notifyWhatsApp',
  'employeeOfMonth:sendCertificateWhatsApp',
  'employeeOfMonth:getHistory', 'employeeOfMonth:delete',
  'jobs:getPostings', 'jobs:savePosting', 'jobs:approvePosting', 'jobs:closePosting', 'jobs:deletePosting', 'jobs:getCandidates', 'jobs:getCandidate', 'jobs:saveCandidate',
  'jobs:requestEmploy', 'jobs:decideCandidate', 'jobs:attachCv', 'jobs:attachPic',
  'jobs:scheduleInterview', 'jobs:waCandidate', 'jobs:waInterviewBulk', 'jobs:interviewDoc',
  'jobs:uploadInterviewResult', 'jobs:approveInterview', 'jobs:getSettings', 'jobs:saveSettings',
  'jobs:getPublicPosting', 'jobs:listPublicPostings', 'jobs:getPublicApplication', 'jobs:lookupPublicApplication',
  'jobs:submitPublicApplication', 'jobs:updatePublicApplication', 'jobs:deletePublicApplication', 'jobs:deleteCandidate',
  'jobs:downloadCv', 'jobs:posterPdf', 'jobs:shareMessage', 'jobs:previewWa',
  'payroll:getSettings', 'payroll:saveSettings', 'payroll:getAdvances', 'payroll:issueAdvance',
  'payroll:getLoans', 'payroll:saveLoan', 'payroll:settleLoan', 'payroll:getDamageCosts', 'payroll:saveDamageCost',
  'payroll:approveDamageCost', 'payroll:getComplianceSubmissions', 'payroll:saveComplianceSubmission',
  'payroll:getComplianceCertificates', 'payroll:saveComplianceCertificate', 'payroll:deleteComplianceCertificate',
  'payroll:getComplianceReminders',
  'payroll:getReport', 'payroll:getStatutoryReport', 'payroll:compliancePdf',
  'ownerSalary:sync', 'ownerSalary:getProfile', 'ownerSalary:saveProfile', 'ownerSalary:deleteProfile',
  'ownerSalary:getPeriods', 'ownerSalary:getPayments', 'ownerSalary:pay',
  'ownerSalary:getNotifications', 'ownerSalary:getReport', 'ownerSalary:payslipPdf', 'ownerSalary:reportPdf',
  'ownerSalary:getDraws', 'ownerSalary:addDraw', 'ownerSalary:deleteDraw',
  'bookkeeping:getSettings', 'bookkeeping:saveSettings', 'bookkeeping:sync', 'bookkeeping:dashboard',
  'bookkeeping:search', 'bookkeeping:getIncome', 'bookkeeping:saveIncome', 'bookkeeping:deleteIncome',
  'bookkeeping:getBank', 'bookkeeping:saveBank', 'bookkeeping:cashBook', 'bookkeeping:bankBook',
  'bookkeeping:payrollAccounting', 'bookkeeping:taxSummary', 'bookkeeping:report', 'bookkeeping:performance',
  'bookkeeping:getBudgets', 'bookkeeping:saveBudget', 'bookkeeping:deleteBudget', 'bookkeeping:budgetVsActual',
  'bookkeeping:getDocuments', 'bookkeeping:saveDocument', 'bookkeeping:deleteDocument',
  'bookkeeping:auditTrail', 'bookkeeping:notifications', 'bookkeeping:categories', 'bookkeeping:reportPdf',
  'donations:get', 'donations:getOne', 'donations:save', 'donations:delete', 'donations:uploadDoc',
  'donations:getDoc', 'donations:submit', 'donations:approve', 'donations:dashboard', 'donations:report',
  'donations:reportPdf', 'donations:reportExcel', 'donations:types',
  'ops:getRules', 'ops:getRule', 'ops:saveRule', 'ops:archiveRule', 'ops:rulePdf', 'ops:allRulesPdf',
  'ops:openingTemplates', 'ops:closingTemplates', 'ops:saveOpeningTemplate', 'ops:saveClosingTemplate',
  'ops:deleteOpeningTemplate', 'ops:deleteClosingTemplate', 'ops:getChecklistRuns', 'ops:getChecklistRun',
  'ops:startChecklist', 'ops:completeChecklistItem', 'ops:finishChecklist', 'ops:submitChecklist',
  'ops:confirmChecklist', 'ops:reopenChecklist', 'ops:adminUpdateChecklist', 'ops:deleteChecklist',
  'ops:pendingChecklists', 'ops:getAdminSignature', 'ops:saveAdminSignature',
  'ops:saveAdminSignatureData', 'ops:getRuleCategories', 'ops:saveRuleCategory', 'ops:getRuleAcks', 'ops:signRule',
  'ops:getChecklistSettings', 'ops:saveChecklistSettings',
  'ops:checklistWarnings', 'ops:staffChecklistWarnings', 'ops:ackChecklistWarning', 'ops:checklistPdf',
  'ops:nonSellingProducts', 'ops:nonSellingExcel', 'ops:nonSellingPdf', 'ops:markProductPromo', 'ops:dashboard',
  'ops:proposePromo', 'ops:pendingPromos', 'ops:promoHistory', 'ops:approvePromo', 'ops:rejectPromo', 'ops:cancelPromo', 'ops:deletePromo', 'ops:updatePromo',
  'ops:promoSalesLog', 'ops:syncPromoStatuses',
  'mo:dashboard', 'mo:home', 'mo:listTasks', 'mo:getTask', 'mo:startTask', 'mo:completeChecklistItem',
  'mo:completeTask', 'mo:verifyTask', 'mo:sales', 'mo:reportProblem', 'mo:listIncidents',
  'mo:teamHelp', 'mo:requestHelp', 'mo:offerHelp', 'mo:submitReport', 'mo:listReports', 'mo:getReport',
  'mo:ownerRespond', 'mo:ackMessage', 'mo:evidence', 'mo:attendance', 'mo:templates', 'mo:saveTemplate',
  'mo:checklists', 'mo:saveChecklist', 'mo:deleteChecklist', 'mo:getSettings', 'mo:saveSettings', 'mo:listAccess', 'mo:listPeople',
  'mo:createTask', 'mo:assignTask', 'mo:assignMany', 'mo:adminComplete', 'mo:listNotifications',
  'mo:resolveIncident', 'mo:markIncidentSeen', 'mo:reportPdf', 'mo:reportPrint',
  'mo:generateTasks',
  'mo:audit', 'mo:categories',
  'combos:get', 'combos:getActive', 'combos:getOne', 'combos:save', 'combos:setStatus', 'combos:approve', 'combos:reject', 'combos:delete',
  'combos:calcPrices', 'combos:report', 'combos:reportPdf', 'combos:reportExcel',
  'recipe:login', 'recipe:sessionFromPos', 'recipe:accessList', 'recipe:listUsers', 'recipe:setAccess', 'recipe:removeAccess',
  'recipe:ingredients', 'recipe:ingredient', 'recipe:list', 'recipe:get', 'recipe:save',
  'recipe:submit', 'recipe:approve', 'recipe:reject', 'recipe:archive', 'recipe:delete',
  'recipe:createProduct', 'recipe:calcCosting', 'recipe:capacity', 'recipe:planProduction',
  'recipe:completeProduction', 'recipe:batches', 'recipe:restock',
  'recipe:wasteList', 'recipe:wasteRecord', 'recipe:wasteApprove', 'recipe:wasteReject',
  'recipe:wasteUpdate', 'recipe:wasteDelete', 'recipe:productionMeals', 'recipe:ingredientStockHistory',
  'recipe:restockPreview', 'recipe:restockBatchHistory', 'recipe:restockBatchDetail', 'recipe:restockBatchSave',
  'recipe:profitsLosses', 'recipe:listPurchaseOrders', 'recipe:ensureMealProfile',
  'recipe:promos', 'recipe:promoSave', 'recipe:dashboard', 'recipe:reports',
  'recipe:ai', 'recipe:applySuggestedPrice', 'recipe:activity', 'recipe:bestSellers', 'recipe:setAvailableToday',
  'recipe:requestSub', 'recipe:listSubs', 'recipe:approveSub', 'recipe:rejectSub', 'recipe:forecast',
  'recipe:mealProducts', 'recipe:getMeal', 'recipe:saveMeal', 'recipe:ingredientCatalog', 'recipe:restockIngredient', 'recipe:ensureIngredient',
  'recipe:updateIngredient', 'recipe:deleteIngredient', 'recipe:restockPlan', 'recipe:setPosMenuFlags', 'recipe:restockList',
  'recipe:ingredientGroups', 'recipe:ingredientGroup', 'recipe:saveIngredientGroup', 'recipe:deleteIngredientGroup', 'recipe:expandIngredientGroups',
  'recipe:productionAvailability', 'recipe:productionDashboard', 'recipe:refreshProduction', 'recipe:productRestock',
  'recipe:createRestockPo', 'recipe:prepBoard', 'recipe:foodCostAlerts', 'recipe:posSubs',
  'recipe:exportBundle', 'recipe:importBundle',
  'acc:login', 'acc:sessionFromPos', 'acc:logout', 'acc:dashboard', 'acc:search', 'acc:settings', 'acc:saveSettings',
  'acc:accounts', 'acc:saveAccount', 'acc:setAccountActive',
  'acc:journals', 'acc:getJournal', 'acc:postJournal', 'acc:publishJournal', 'acc:reverseJournal', 'acc:ledger',
  'acc:trialBalance', 'acc:profitLoss', 'acc:balanceSheet', 'acc:cashFlow',
  'acc:periods', 'acc:closePeriod', 'acc:reopenPeriod', 'acc:lockPeriod', 'acc:yearEnd',
  'acc:invoices', 'acc:getInvoice', 'acc:saveInvoice', 'acc:postInvoice',
  'acc:creditNotes', 'acc:saveCreditNote', 'acc:postCreditNote',
  'acc:debitNotes', 'acc:saveDebitNote',
  'acc:bills', 'acc:saveBill', 'acc:postBill',
  'acc:payments', 'acc:savePayment', 'acc:refunds', 'acc:saveRefund',
  'acc:agingAr', 'acc:agingAp', 'acc:customerStatement', 'acc:supplierStatement',
  'acc:bankAccounts', 'acc:saveBankAccount', 'acc:bankTxns', 'acc:saveBankTxn',
  'acc:importBankStmt', 'acc:matchBankStmt', 'acc:createReconciliation', 'acc:completeReconciliation',
  'acc:cashAccounts', 'acc:cashTxns', 'acc:saveCashTxn', 'acc:pettyCash', 'acc:savePettyCash', 'acc:cashupFinance',
  'acc:expenses', 'acc:recordExpense', 'acc:recurring', 'acc:saveRecurring', 'acc:processRecurring',
  'acc:otherIncome', 'acc:saveOtherIncome',
  'acc:assets', 'acc:saveAsset', 'acc:runDepreciation',
  'acc:loans', 'acc:saveLoan', 'acc:loanPayment',
  'acc:ownerTxns', 'acc:saveOwnerTxn',
  'acc:taxRates', 'acc:saveTaxRate', 'acc:taxSummary',
  'acc:salesReport', 'acc:purchaseReport', 'acc:expenseReport', 'acc:stockValue', 'acc:drillDown',
  'acc:documents', 'acc:saveDocument', 'acc:recordStockAdjustment', 'acc:stockAdjustments', 'acc:getDocumentFile', 'acc:processOcr', 'acc:confirmOcr',
  'acc:flushIntegrations', 'acc:reflushFailedIntegrations',
  'delivery:dashboard', 'delivery:list', 'delivery:get', 'delivery:drivers', 'delivery:getDriver', 'delivery:saveDriver',
  'delivery:approveDriver', 'delivery:rejectDriver', 'delivery:registerDriver', 'delivery:adminRegisterDriver',
  'delivery:releaseToPool', 'delivery:assign', 'delivery:autoAssign', 'delivery:assignMultiple',
  'delivery:updateStatus', 'delivery:updateDelivery', 'delivery:cancelDelivery',
  'delivery:settings', 'delivery:saveSettings', 'delivery:branchSettings', 'delivery:saveBranchSettings',
  'delivery:listBranchSettings', 'delivery:deleteBranchSettings', 'delivery:suspendDriver', 'delivery:deleteDriver',
  'delivery:driverEarnings', 'delivery:reports', 'delivery:tracking',
  'delivery:driverPaymentSummary', 'delivery:previewDriverPayout', 'delivery:recordDriverPayout',
  'delivery:driverPayoutHistory', 'delivery:listPayoutClaims', 'delivery:approvePayoutClaim', 'delivery:rejectPayoutClaim',
  'driver:login', 'driver:logout', 'driver:dashboard', 'driver:orders', 'driver:accept', 'driver:reject',
  'driver:release', 'driver:updateStatus', 'driver:availability', 'driver:history', 'driver:earnings',
  'driver:payments', 'driver:profile', 'driver:updateProfile', 'driver:submitClaim',
  'referral:dashboard', 'referral:applications', 'referral:getAgent', 'referral:approveAgent', 'referral:rejectAgent',
  'referral:underReview', 'referral:suspendAgent', 'referral:unsuspendAgent', 'referral:updateAgent',
  'referral:deleteAgent', 'referral:clearAttribution', 'referral:clearSaleReferral', 'referral:awardCommission', 'referral:listAwardRequests', 'referral:getAwardRequest', 'referral:decideAwardRequest',
  'referral:searchCodes', 'referral:agents', 'referral:commissions', 'referral:approveCommission',
  'referral:markAvailable', 'referral:payouts', 'referral:getPayout', 'referral:generatePayout', 'referral:approvePayout',
  'referral:markPayoutPaid', 'referral:settings', 'referral:updateSettings', 'referral:attributions', 'referral:codes',
  'referral:topAgents', 'referral:audit', 'referral:fraud', 'referral:approveBankChange', 'referral:apply',
  'referral:agentDashboard', 'referral:unreadNotifications', 'referral:ackNotification', 'referral:ackAllNotifications',
  'referral:requestBankChange', 'referral:validateCode', 'referral:recordClick', 'referral:attribute',
  'referral:resetAgentPassword', 'referral:ensureAgentLogin',
  'acc:approvals', 'acc:decideApproval',
  'acc:notifications', 'acc:readNotification', 'acc:audit',
  'acc:integrations', 'acc:retryIntegration',
  'acc:financialHealth', 'acc:reconcileCentre', 'acc:bankStmtLines', 'acc:listCashupFinance', 'acc:syncMissing',
  'hr:login', 'hr:dashboard', 'hr:search', 'hr:settings', 'hr:saveSettings', 'hr:people', 'hr:listPayroll',
  'hr:attendanceHub', 'hr:schedules', 'hr:leaveBalances', 'hr:employeeDocuments', 'hr:offboardingList',
  'hr:onboardingList', 'hr:payrollDeductions', 'hr:statutorySummary', 'hr:performanceHub', 'hr:staffWarnings',
  'hr:employeeProfile',
  'hr:employeeTimeline', 'hr:approvals', 'hr:submitForApproval', 'hr:complianceCentre', 'hr:complianceEvents', 'hr:saveComplianceEvent',
  'hr:policies', 'hr:savePolicy', 'hr:acknowledgePolicy', 'hr:businessRules', 'hr:saveBusinessRule',
  'hr:incidents', 'hr:saveIncident', 'hr:disciplinaryCases', 'hr:saveDisciplinaryCase',
  'mgrHr:listAssignments', 'mgrHr:getAssignment', 'mgrHr:saveAssignment', 'mgrHr:setAssignmentActive',
  'mgrHr:listEligibleUsers', 'mgrHr:listActivity', 'mgrHr:portalContext', 'mgrHr:dashboard', 'mgrHr:listMyStaff',
  'mgrHr:listCases', 'mgrHr:getCase', 'mgrHr:createCase', 'mgrHr:updateStatus', 'mgrHr:requestResponse',
  'mgrHr:addRecommendation', 'mgrHr:createWarning', 'mgrHr:adminDecide', 'mgrHr:deleteCase', 'mgrHr:listNotifications',
  'mgrHr:markNotificationRead', 'mgrHr:listEmployeeCases', 'mgrHr:getEmployeeCase', 'mgrHr:submitEmployeeResponse',
  'mgrHr:listRecordings', 'mgrHr:getRecording', 'mgrHr:createRecording', 'mgrHr:updateRecording',
  'mgrHr:deleteRecording', 'mgrHr:analyzeRecording', 'mgrHr:recordingDocumentHtml', 'mgrHr:caseDocumentHtml',
  'hr:onboardingTemplates',
  'hr:onboardingProgress', 'hr:saveOnboardingProgress', 'hr:forms', 'hr:saveForm', 'hr:createExternalLink',
  'hr:requests', 'hr:saveRequest', 'hr:decideRequest', 'hr:employerRecords', 'hr:saveEmployerRecord',
  'hr:salaryHistory', 'hr:saveSalaryChange', 'hr:saveOffboarding', 'hr:postPayrollAccounting',
  'acc:purchaseOrders', 'acc:payroll', 'acc:integrate', 'acc:flushIntegrations',
  'whatsapp:getTemplates', 'whatsapp:getTemplate', 'whatsapp:saveTemplate', 'whatsapp:deleteTemplate',
  'whatsapp:getMessages', 'whatsapp:send', 'whatsapp:markOpened', 'whatsapp:getAudience',
  'whatsapp:getCampaigns', 'whatsapp:getCampaign', 'whatsapp:saveCampaign', 'whatsapp:deleteCampaign',
  'whatsapp:sendCampaign', 'whatsapp:getSettings', 'whatsapp:saveSettings',
  'documentHub:get', 'documentHub:getOne', 'documentHub:save', 'documentHub:delete',
  'documentHub:share', 'documentHub:exportStatus', 'documentHub:processScheduled',
  'rewards:getRules', 'rewards:saveRule', 'rewards:deleteRule',
  'firstOnlineGift:get', 'firstOnlineGift:save', 'firstOnlineGift:dashboard', 'firstOnlineGift:winners', 'firstOnlineGift:selfTest',
  'paymentGateways:list', 'paymentGateways:save', 'paymentGateways:test', 'paymentGateways:registerWebhook',
  'paymentGateways:listTransactions', 'paymentGateways:refund',
  'web:startOnlinePayment', 'web:getPaymentStatus',
  'branches:get', 'branches:getActive', 'branches:getView', 'branches:setView', 'branches:save', 'branches:setActive', 'branches:saveSettings',
  'bizModules:settings', 'bizModules:saveSettings', 'bizModules:summary',
  'investor:login', 'investor:logout', 'investor:dashboard', 'investor:list', 'investor:get', 'investor:save',
  'investor:createPortalUser', 'investor:saveProposal', 'investor:listProposals', 'investor:proposalPdf',
  'investor:saveAgreement', 'investor:uploadDocument', 'investor:recordPayment', 'investor:recordDistribution', 'investor:summary',
  'release:login', 'release:logout', 'release:dashboard', 'release:runTests', 'release:createVersion', 'release:approve', 'release:publish',
  'release:listUsers', 'release:saveUser', 'release:summary',
  'meeting:login', 'meeting:logout', 'meeting:list', 'meeting:get', 'meeting:save', 'meeting:start', 'meeting:stop',
  'meeting:saveRecording', 'meeting:saveTranscript', 'meeting:processAi', 'meeting:finalizeMinutes', 'meeting:search', 'meeting:ask',
  'meeting:listUsers', 'meeting:saveUser', 'meeting:summary',
  'signage:login', 'signage:logout', 'signage:dashboard', 'signage:summary', 'signage:requestPairing', 'signage:pairingStatus',
  'signage:pendingPairings', 'signage:approvePairing', 'signage:rejectPairing', 'signage:revokeDevice', 'signage:listDevices',
  'signage:saveDevice', 'signage:listMedia', 'signage:uploadMedia', 'signage:deleteMedia', 'signage:listPlaylists',
  'sync:getStatus', 'sync:saveSettings', 'sync:register', 'sync:now', 'sync:publishProducts',
  'sync:branchesToHub', 'sync:getOnlineOrders', 'sync:importCloudOrders', 'sync:updateOnlineOrder', 'sync:rejectOnlineOrder', 'sync:acceptOnlineOrder',
  'web:getSettings', 'web:getHoursStatus', 'web:trackEvents', 'web:visitorDashboard', 'web:onlineCustomers', 'web:getBranches', 'web:getMenu', 'web:getProduct', 'web:register', 'web:login',
  'web:sendPasswordReset', 'web:resetPassword',
  'web:account', 'web:validateCart', 'web:validateCoupon', 'web:submitOrder', 'web:getOrder', 'web:listOrders',
  'web:toggleFavorite', 'web:checkGiftCard', 'web:deleteAccount',
  'web:submitIssue', 'web:listMyIssues', 'web:listIssues', 'web:getIssue', 'web:replyIssue',
  'web:adminOrders', 'web:adminOrderDetail', 'web:adminUpdateOrder', 'web:adminDeleteOrder',
  'web:adminAnalytics', 'web:saveGlobalSettings', 'web:saveBranchSettings',
  'branches:delete', 'branches:listTills', 'branches:saveTill', 'branches:updateTill', 'branches:deleteTill',
  'web:getBranchSettings', 'web:rejectOrder', 'web:rejectedOrdersReport', 'auth:recoverDriverPassword', 'auth:recoverReferralAgentPassword', 'auth:resetReferralAgentPassword', 'auth:recoverAdminPassword', 'web:updateOrderStatus',
  'mobile:login', 'mobile:bootstrapAdmin', 'mobile:logout', 'mobile:profile', 'mobile:dashboard', 'mobile:heartbeat',
  'mobile:orders', 'mobile:order', 'mobile:searchOrders', 'mobile:staffActivity', 'mobile:posStatus',
  'mobile:alerts', 'mobile:markRead', 'mobile:getPrefs', 'mobile:savePrefs', 'mobile:registerPush', 'mobile:poll',
  'mobile:adminListUsers', 'mobile:adminGetUser', 'mobile:adminSaveUser', 'mobile:adminSetActive',
  'mobile:adminListDevices', 'mobile:adminRevokeDevice',
  'tables:delete', 'reports:orderTypes', 'store:runStartupTasks', 'settings:saveKdsSound',
  'backup:getInfo'
];

const api = {};
channels.forEach(ch => {
  api[ch.replace(/[:]/g, '_')] = (...args) => ipcRenderer.invoke(ch, ...args);
});
api.onKitchenRefresh = (cb) => {
  ipcRenderer.on('kitchen:refresh', cb);
  return () => ipcRenderer.removeListener('kitchen:refresh', cb);
};
api.onAppCloseBlocked = (cb) => {
  const handler = () => cb();
  ipcRenderer.on('app:close-blocked', handler);
  return () => ipcRenderer.removeListener('app:close-blocked', handler);
};
contextBridge.exposeInMainWorld('posAPI', api);

// When Supabase is configured, renderer bootstrap replaces posAPI for data channels.
// Keep IPC posAPI available only as fallback until bootstrap runs.

