-- Multi-branch (Railway / Supabase)
CREATE TABLE IF NOT EXISTS public.branch_stock (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  branch_id bigint NOT NULL REFERENCES public.branches(id) ON DELETE CASCADE,
  quantity numeric NOT NULL DEFAULT 0,
  min_stock numeric DEFAULT 0,
  updated_at text DEFAULT now(),
  UNIQUE(product_id, branch_id)
);

CREATE TABLE IF NOT EXISTS public.branch_settings (
  branch_id bigint PRIMARY KEY REFERENCES public.branches(id) ON DELETE CASCADE,
  tax_enabled integer DEFAULT 0,
  tax_rate numeric DEFAULT 0,
  tax_inclusive integer DEFAULT 1,
  tax_show_on_pos integer DEFAULT 1,
  vat_number text,
  updated_at text DEFAULT now()
);

ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id);
ALTER TABLE public.employees ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id);
ALTER TABLE public.shop_settings ADD COLUMN IF NOT EXISTS view_branch_id bigint;
ALTER TABLE public.stock_movements ADD COLUMN IF NOT EXISTS branch_id bigint;
